import"./assets/styles-BK7AYJoX.js";import{a as r}from"./assets/vendor-N5iQpiFS.js";r.defaults.baseURL="https://dummyjson.com";async function p(){const s=await r.get("/products/category-list");return console.log(s.data),s.data}async function i(){const e=await r.get("https://dummyjson.com/products?limit=12&skip=0");return console.log(e.data.products),e.data.products}async function u(s){const t=await r.get(`/products/category/${s}`);return console.log(t.data.products),t.data.products}const o={allCategories:document.querySelector(".categories"),allProducts:document.querySelector(".products"),notFound:document.querySelector(".not-found")};function g(s){o.allCategories.innerHTML="";const t=s.map(e=>`<li class="categories__item">
        <button class="categories__btn" type="button">${e}</button>
      </li>`).join("");o.allCategories.innerHTML=t}function n(s){o.allProducts.innerHTML="";const t=s.map(e=>`<li class="products__item" data-id="${e.id}">
        <img class="products__image" src="${e.thumbnail}" alt="${e.title}"/>
        <p class="products__title">${e.title}</p>
        <p class="products__brand"><span class="products__brand--bold">Brand:</span> ${e.brand}</p>
        <p class="products__category">Category: ${e.category}</p>
        <p class="products__price">Price: $${e.price}</p>
      </li>`).join("");o.allProducts.innerHTML=t}async function m(){const t=["All",...await p()];g(t)}m();async function _(){const s=await i();n(s)}_();o.allCategories.addEventListener("click",y);async function y(s){const t=s.target.closest(".categories__btn");if(!t)return;if(t.textContent.trim()==="All"){const a=await i();n(a)}else{const a=t.textContent.trim(),d=await u(a);n(d)}const e=t.textContent.trim(),l=o.allCategories.querySelector(".categories__btn--active");l&&l.classList.remove("categories__btn--active"),t.classList.add("categories__btn--active");let c=[];try{e==="All"?c=await i():c=await u(e),c.length?(o.notFound.classList.remove("not-found--visible"),n(c)):(o.notFound.classList.add("not-found--visible"),o.allProducts.innerHTML="")}catch(a){console.error("😿 Не вдалося отримати продукти:",a)}}
//# sourceMappingURL=index.js.map
